// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/kelompok43/Golang/admin/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *Repository) Create(_a0 domain.Admin) (domain.Admin, error) {
	ret := _m.Called(_a0)

	var r0 domain.Admin
	if rf, ok := ret.Get(0).(func(domain.Admin) domain.Admin); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Admin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Admin) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *Repository) Get() ([]domain.Admin, error) {
	ret := _m.Called()

	var r0 []domain.Admin
	if rf, ok := ret.Get(0).(func() []domain.Admin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Admin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: email
func (_m *Repository) GetByEmail(email string) (domain.Admin, error) {
	ret := _m.Called(email)

	var r0 domain.Admin
	if rf, ok := ret.Get(0).(func(string) domain.Admin); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(domain.Admin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id int) (domain.Admin, error) {
	ret := _m.Called(id)

	var r0 domain.Admin
	if rf, ok := ret.Get(0).(func(int) domain.Admin); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Admin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *Repository) Update(_a0 domain.Admin) (domain.Admin, error) {
	ret := _m.Called(_a0)

	var r0 domain.Admin
	if rf, ok := ret.Get(0).(func(domain.Admin) domain.Admin); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Admin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Admin) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
